spring.application.name=demo
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

file.upload-dir=${UPLOAD_DIR}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=9v5x0NytwES6ALo2BlFwZYBpfjRHvbvjEGHHpl3tenh

logging.level.org.springframework.http.converter.json=TRACE
logging.level.com.fasterxml.jackson.databind=TRACE
server.error.include-message=always
server.error.include-binding-errors=always